# Generated by Django 5.2 on 2025-05-13 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='website',
            name='manager_email',
            field=models.EmailField(blank=True, help_text='Email address for the website manager', max_length=255),
        ),
        migrations.AlterField(
            model_name='website',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='website',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
