# Generated by Django 5.2 on 2025-05-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_website_updated_at_website_manager_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='manager_email',
            field=models.EmailField(blank=True, help_text='Email address for the website manager', max_length=255, null=True),
        ),
    ]
